name: Checkout Development Build

on:
    push:
        branches:
            - 'development'

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [16.x]

        steps:
            - name: Checkout
              uses: actions/checkout@v1
